#!/bin/bash

if [ ! -d "$ACBOOST_ROOT" ]; then
  ACBOOST_ROOT=$(dirname "$0")
fi

if [ -z "$ACBOOST_DIRPREFIX" ]; then
  ACBOOST_DIRPREFIX=$(date +%Y)
fi

problem_name=$1
problem_url=$2
problem_dir="$ACBOOST_DIRPREFIX/$problem_name"

if [ -z $problem_name ]; then
  echo "Usage: $0 <problem_name> [problem_url]"
  return 1 2>/dev/null
  exit 1
fi

mkdir -p $ACBOOST_DIRPREFIX
mkdir $problem_dir
if [ $? != 0 ]; then
  return 1 2>/dev/null
  exit 1
fi

mkdir $problem_dir/src
mkdir $problem_dir/cases
mkdir $problem_dir/build

touch $problem_dir/cases/1.in
touch $problem_dir/cases/1.out

touch $problem_dir/src/$problem_name.cpp
echo "// Problem Alias: $problem_name" >> $problem_dir/src/$problem_name.cpp
if [[ ! -z "$problem_url" ]]; then
  echo "// Url: $problem_url" >> $problem_dir/src/$problem_name.cpp
fi

ln $ACBOOST_ROOT/templates/makefile_template $problem_dir/makefile

pushd $problem_dir >/dev/null
