#!/bin/bash

problem_name=$1
problem_url=$2
problem_dir=$(date +%Y)/$problem_name

if [ -z $problem_name ]; then
  echo "Usage: $0 <problem_name> [problem_url]"
  exit 1
fi

mkdir $problem_dir
if [ $? != 0 ]; then
  exit 1
fi

mkdir $problem_dir/src
mkdir $problem_dir/cases
mkdir $problem_dir/build

touch $problem_dir/cases/1.in
touch $problem_dir/cases/1.out

touch $problem_dir/src/$problem_name.cpp
echo "// Problem Alias: $problem_name" >> $problem_dir/src/$problem_name.cpp
if [[ ! -z "$problem_url" ]]; then
  echo "// Url: $problem_url" >> $problem_dir/src/$problem_name.cpp
fi

ln makefile_template $problem_dir/makefile

pushd $problem_dir >/dev/null
